name: "Renovate Updates"

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

env:
  LOG_LEVEL: debug

jobs:
  renovate-updates:
    name: "Renovate Updates"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.3
        with:
          configurationFile: ./.github/renovate-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
